[package]
name = "chess_engine"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.4"
directories-next = "2.0"
rusqlite = { version = "0.33.0", features = ["bundled"] }
serde = { version = "1.0", features = ["derive"] }
sha2 = "0.9"
regex = "1.11.1"